state_fips = {
    "Alabama" : "01",
    "Alaska" : "02",
    "Arizona" : "04",
    "Arkansas" : "05",
    "California" : "06",
    "Colorado" : "08",
    "Connecticut" : "09",
    "Delaware" : "10",
    "District of Columbia" : "11",
    "Florida" : "12",
    "Georgia" : "13",
    "Hawaii" : "15",
    "Idaho" : "16",
    "Illinois" : "17",
    "Indiana" : "18",
    "Iowa" : "19",
    "Kansas" : "20",
    "Kentucky" : "21",
    "Louisiana" : "22",
    "Maine" : "23",
    "Maryland" : "24",
    "Massachusetts" : "25",
    "Michigan" : "26",
    "Minnesota" : "27",
    "Mississippi" : "28",
    "Missouri" : "29",
    "Montana" : "30",
    "Nebraska" : "31",
    "Nevada" : "32",
    "New Hampshire" : "33",
    "New Jersey" : "34",
    "New Mexico" : "35",
    "New York" : "36",
    "North Carolina" : "37",
    "North Dakota" : "38",
    "Ohio" : "39",
    "Oklahoma" : "40",
    "Oregon" : "41",
    "Pennsylvania" : "42",
    "Rhode Island" : "44",
    "South Carolina" : "45",
    "South Dakota" : "46",
    "Tennessee" : "47",
    "Texas" : "48",
    "Utah" : "49",
    "Vermont" : "50",
    "Virginia" : "51",
    "Washington" : "53",
    "West Virginia" : "54",
    "Wisconsin" : "55",
    "Wyoming" : "56"
}
fips_state = {
 '01': 'Alabama',
 '02': 'Alaska',
 '04': 'Arizona',
 '05': 'Arkansas',
 '06': 'California',
 '08': 'Colorado',
 '09': 'Connecticut',
 '10': 'Delaware',
 '11': 'District of Columbia',
 '12': 'Florida',
 '13': 'Georgia',
 '15': 'Hawaii',
 '16': 'Idaho',
 '17': 'Illinois',
 '18': 'Indiana',
 '19': 'Iowa',
 '20': 'Kansas',
 '21': 'Kentucky',
 '22': 'Louisiana',
 '23': 'Maine',
 '24': 'Maryland',
 '25': 'Massachusetts',
 '26': 'Michigan',
 '27': 'Minnesota',
 '28': 'Mississippi',
 '29': 'Missouri',
 '30': 'Montana',
 '31': 'Nebraska',
 '32': 'Nevada',
 '33': 'New Hampshire',
 '34': 'New Jersey',
 '35': 'New Mexico',
 '36': 'New York',
 '37': 'North Carolina',
 '38': 'North Dakota',
 '39': 'Ohio',
 '40': 'Oklahoma',
 '41': 'Oregon',
 '42': 'Pennsylvania',
 '44': 'Rhode Island',
 '45': 'South Carolina',
 '46': 'South Dakota',
 '47': 'Tennessee',
 '48': 'Texas',
 '49': 'Utah',
 '50': 'Vermont',
 '51': 'Virginia',
 '53': 'Washington',
 '54': 'West Virginia',
 '55': 'Wisconsin',
 '56': 'Wyoming'
 }
state_postal = {
        "Alabama" : "AL",
        "Alaska" : "AK",
        "Arizona" : "AZ",
        "Arkansas" : "AR",
        "California" : "CA",
        "Colorado" : "CO",
        "Connecticut" : "CT",
        "Delaware" : "DE",
        "District of Columbia" : "DC",
        "Florida" : "FL",
        "Georgia" : "GA",
        "Hawaii" : "HI",
        "Idaho" : "ID",
        "Illinois" : "IL",
        "Indiana" : "IN",
        "Iowa" : "IA",
        "Kansas" : "KS",
        "Kentucky" : "KY",
        "Louisiana" : "LA",
        "Maine" : "ME",
        "Maryland" : "MD",
        "Massachusetts" : "MA",
        "Michigan" : "MI",
        "Minnesota" : "MN",
        "Mississippi" : "MS",
        "Missouri" : "MO",
        "Montana" : "MT",
        "Nebraska" : "NE",
        "Nevada" : "NV",
        "New Hampshire" : "NH",
        "New Jersey" : "NJ",
        "New Mexico" : "NM",
        "New York" : "NY",
        "North Carolina" : "NC",
        "North Dakota" : "ND",
        "Ohio" : "OH",
        "Oklahoma" : "OK",
        "Oregon" : "OR",
        "Pennsylvania" : "PA",
        "Rhode Island" : "RI",
        "South Carolina" : "SC",
        "South Dakota" : "SD",
        "Tennessee" : "TN",
        "Texas" : "TX",
        "Utah" : "UT",
        "Vermont" : "VT",
        "Virginia" : "VA",
        "Washington" : "WA",
        "West Virginia" : "WV",
        "Wisconsin" : "WI",
        "Wyoming" : "WY"
       }
fips_postal = {
 '01': 'AL',
 '02': 'AK',
 '04': 'AZ',
 '05': 'AR',
 '06': 'CA',
 '08': 'CO',
 '09': 'CT',
 '10': 'DE',
 '11': 'DC',
 '12': 'FL',
 '13': 'GA',
 '15': 'HI',
 '16': 'ID',
 '17': 'IL',
 '18': 'IN',
 '19': 'IA',
 '20': 'KS',
 '21': 'KY',
 '22': 'LA',
 '23': 'ME',
 '24': 'MD',
 '25': 'MA',
 '26': 'MI',
 '27': 'MN',
 '28': 'MS',
 '29': 'MO',
 '30': 'MT',
 '31': 'NE',
 '32': 'NV',
 '33': 'NH',
 '34': 'NJ',
 '35': 'NM',
 '36': 'NY',
 '37': 'NC',
 '38': 'ND',
 '39': 'OH',
 '40': 'OK',
 '41': 'OR',
 '42': 'PA',
 '44': 'RI',
 '45': 'SC',
 '46': 'SD',
 '47': 'TN',
 '48': 'TX',
 '49': 'UT',
 '50': 'VT',
 '51': 'VA',
 '53': 'WA',
 '54': 'WV',
 '55': 'WI',
 '56': 'WY'}
